import '../../data/models/dua_model.dart';

const List<DuaItem> staticDuas = [
  // ── 1. Sleep / ঘুম সম্পর্কিত ──────────────────────────────────────────────
  DuaItem(
    titleEn: 'Before Sleeping',
    titleBn: 'ঘুমানোর দোয়া',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    translationEn: 'In Your name, O Allah, I die and I live.',
    translationBn: 'হে আল্লাহ! আপনার নামে আমি মৃত্যুবরণ করি (ঘুমাই) এবং জীবিত হই (জাগি)।',
    pronunciationEn: 'Bismika Allahumma amutu wa ahya.',
    pronunciationBn: 'বিইসমিকা আল্লাহুম্মা আমূতু ওয়া আহয়া।',
    categoryEn: 'Sleep',
    categoryBn: 'ঘুম সম্পর্কিত',
  ),
  DuaItem(
    titleEn: 'Upon Waking Up',
    titleBn: 'ঘুম থেকে ওঠার দোয়া',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    translationEn: 'Praise is to Allah Who gives us life after He has caused us to die and unto Him is the resurrection.',
    translationBn: 'সব প্রশংসা আল্লাহর জন্য যিনি মৃত্যুর পর আমাদের জীবিত করলেন এবং তাঁর দিকেই ফিরে যেতে হবে।',
    pronunciationEn: 'Alhamdulillahilladhi ahyana ba\'da ma amatana wa ilayhin-nushur.',
    pronunciationBn: 'আলহামদু লিল্লাহিল্লাজী আহইয়ানা বা’দা মা আমাতানা ওয়া ইলাইহিন নুশূর।',
    categoryEn: 'Sleep',
    categoryBn: 'ঘুম সম্পর্কিত',
  ),
  DuaItem(
    titleEn: 'Dua After a Bad Dream',
    titleBn: 'দুঃস্বপ্ন দেখলে দোয়া',
    arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
    translationEn: 'I seek refuge in Allah from the accursed devil (spit lightly three times over your left shoulder).',
    translationBn: 'আমি বিতাড়িত শয়তান থেকে আল্লাহর আশ্রয় প্রার্থনা করছি (এবং বাম কাঁধের উপর দিয়ে ৩ বার হালকা থুতু ফেলুন)।',
    pronunciationEn: 'A\'udhu billahi minash-shaytanir-rajim.',
    pronunciationBn: 'আউজু বিল্লাহি মিনাশ শাইতানির রাজিম।',
    categoryEn: 'Sleep',
    categoryBn: 'ঘুম সম্পর্কিত',
  ),
  DuaItem(
    titleEn: 'Dua After a Good Dream',
    titleBn: 'ভালো স্বপ্ন দেখলে করণীয়',
    arabic: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
    translationEn: 'Praise be to Allah, Lord of the worlds (only tell those whom you love).',
    translationBn: 'সকল প্রশংসা বিশ্বজগতের প্রতিপালক আল্লাহর জন্য (এবং এই স্বপ্ন শুধু তাকেই বলুন যে আপনাকে ভালোবাসে)।',
    pronunciationEn: 'Alhamdulillahi Rabbil \'Alamin.',
    pronunciationBn: 'আলহামদুলিল্লাহি রাব্বিল আলামিন।',
    categoryEn: 'Sleep',
    categoryBn: 'ঘুম সম্পর্কিত',
  ),

  // ── 2. Home / ঘর সম্পর্কিত ───────────────────────────────────────────────
  DuaItem(
    titleEn: 'Entering the Home',
    titleBn: 'ঘরে প্রবেশের দোয়া',
    arabic: 'بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا',
    translationEn: 'In the name of Allah we enter, in the name of Allah we leave, and upon our Lord we depend.',
    translationBn: 'আমরা আল্লাহর নামে প্রবেশ করলাম, আল্লাহর নামে বের হলাম এবং আমাদের প্রতিপালক আল্লাহর ওপর ভরসা করলাম।',
    pronunciationEn: 'Bismillaahi walajnaa, wa bismillaahi kharajnaa, wa \'alaa-llaahi Rabbinaa tawakkalnaa.',
    pronunciationBn: 'বিসমিল্লাহি ওয়ালাজনা, ওয়া বিসমিল্লাহি খারাজনা, ওয়া আলাল্লাহি রাব্বিনা তাওয়াক্কালনা।',
    categoryEn: 'Home',
    categoryBn: 'ঘর সম্পর্কিত',
  ),
  DuaItem(
    titleEn: 'Leaving the Home',
    titleBn: 'ঘর থেকে বের হওয়ার দোয়া',
    arabic: 'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    translationEn: 'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.',
    translationBn: 'আল্লাহর নামে, আমি আল্লাহর ওপর ভরসা করলাম। আল্লাহর সাহায্য ছাড়া গুনাহ থেকে বাঁচার এবং নেক কাজ করার কোনো শক্তি নেই।',
    pronunciationEn: 'Bismillaahi tawakkaltu \'ala Allahi, wa laa hawla wa laa quwwata illaa billaah.',
    pronunciationBn: 'বিসমিল্লাহি তাওয়াক্কালতু আলাল্লাহি, ওয়ালা হাওলা ওয়ালা কুয়াতা ইল্লা বিল্লাহ।',
    categoryEn: 'Home',
    categoryBn: 'ঘর সম্পর্কিত',
  ),
  DuaItem(
    titleEn: 'Entering a New Home',
    titleBn: 'নতুন ঘরে প্রবেশের দোয়া',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    translationEn: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
    translationBn: 'আল্লাহর পরিপূর্ণ কালিমাসমূহের উসিলায় তাঁর সৃষ্টির সমস্ত অনিষ্ট থেকে আশ্রয় চাই।',
    pronunciationEn: 'A\'udhu bi kalimaati-llaahit-taammaati min sharri maa khalaq.',
    pronunciationBn: 'আউজু বিকালি মাতিল্লাহিত তাম্মাতি مين শাররি মা খালাক।',
    categoryEn: 'Home',
    categoryBn: 'ঘর সম্পর্কিত',
  ),

  // ── 3. Toilet / টয়লেট ──────────────────────────────────────────────────
  DuaItem(
    titleEn: 'Entering the Toilet',
    titleBn: 'টয়লেটে প্রবেশের দোয়া',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
    translationEn: 'O Allah, I seek refuge with You from the bad and evil spirits (male and female devils).',
    translationBn: 'হে আল্লাহ! আমি আপনার নিকট অপবিত্র নর ও নারী শয়তানদের অনিষ্ট থেকে আশ্রয় চাচ্ছি।',
    pronunciationEn: 'Allahumma innee a\'udhu bika minal-khubuthi wal-khabaa\'ith.',
    pronunciationBn: 'আল্লাহুম্মা ইন্নি আউজু বিকা মিনাল খুবুসি ওয়াল খাবায়িস।',
    categoryEn: 'Toilet',
    categoryBn: 'টয়লেট',
  ),
  DuaItem(
    titleEn: 'Leaving the Toilet',
    titleBn: 'টয়লেট থেকে বের হওয়ার দোয়া',
    arabic: 'غُفْرَانَكَ',
    translationEn: 'I ask You for Your forgiveness.',
    translationBn: 'হে আল্লাহ! আমি আপনার নিকট ক্ষমা প্রার্থনা করছি।',
    pronunciationEn: 'Ghufranak.',
    pronunciationBn: 'গুফরানাকা।',
    categoryEn: 'Toilet',
    categoryBn: 'টয়লেট',
  ),

  // ── 4. Ablution & Prayer / ওযু ও নামাজ ──────────────────────────────────
  DuaItem(
    titleEn: 'Before Ablution (Wudu)',
    titleBn: 'ওযুর আগে দোয়া',
    arabic: 'بِسْمِ اللَّهِ',
    translationEn: 'In the name of Allah.',
    translationBn: 'আল্লাহর নামে (শুরু করছি)।',
    pronunciationEn: 'Bismillah.',
    pronunciationBn: 'বিসমিল্লাহ।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'After Ablution (Wudu)',
    titleBn: 'ওযুর পরে দোয়া',
    arabic: 'أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ',
    translationEn: 'I bear witness that there is no god but Allah alone, without partner, and I bear witness that Muhammad is His servant and Messenger.',
    translationBn: 'আমি সাক্ষ্য দিচ্ছি যে, এক আল্লাহ ছাড়া কোনো উপাস্য নেই, তাঁর কোনো শরিক নেই এবং আমি আরও সাক্ষ্য দিচ্ছি যে, মুহাম্মদ আল্লাহর বান্দা ও রাসুল।',
    pronunciationEn: 'Ashhadu an laa ilaaha illallaahu wahdahu laa shareeka lahu wa ashhadu anna Muhammadan \'abduhu wa Rasooluhu.',
    pronunciationBn: 'আশহাদু আল্লা ইলাহা ইল্লাল্লাহু ওয়াহদাহু লা শারীকা লাহু ওয়া আশহাদু আন্না মুহাম্মাদান আবদুহু ওয়া রাসূলুহু।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'Entering the Mosque',
    titleBn: 'মসজিদে প্রবেশের দোয়া',
    arabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    translationEn: 'O Allah, open for me the gates of Your mercy.',
    translationBn: 'হে আল্লাহ! আমার জন্য আপনার রহমতের দরজাগুলো খুলে দিন।',
    pronunciationEn: 'Allahumma-ftah lee abwaaba rahmatik.',
    pronunciationBn: 'আল্লাহুম্মাফ তাহলী আবওয়াবা রাহমাতিকা।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'Leaving the Mosque',
    titleBn: 'মসজিদ থেকে বের হওয়ার দোয়া',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
    translationEn: 'O Allah, I ask You from Your bounty.',
    translationBn: 'হে আল্লাহ! আমি আপনার নিকট আপনার অনুগ্রহ প্রার্থনা করছি।',
    pronunciationEn: 'Allahumma innee as\'aluka min fadlik.',
    pronunciationBn: 'আল্লাহুম্মা ইন্নি আসআলুকা মিন ফাদলিকা।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'Opening Dua (Istiftah)',
    titleBn: 'ইস্তিফতাহ দোয়া (ছানা)',
    arabic: 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبَارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلَا إِلَهَ غَيْرُكَ',
    translationEn: 'Glory is to You, O Allah, and praise. Blessed is Your name and exalted is Your majesty, and there is no god other than You.',
    translationBn: 'হে আল্লাহ! আমি আপনার সপ্রশংস পবিত্রতা ঘোষণা করছি, আপনার নাম বরকতময়, আপনার মহিমা অতি উচ্চ এবং আপনি ব্যতীত কোনো সত্য মাবুদ নেই।',
    pronunciationEn: 'Subhaanaka Allahumma wa bihamdika, wa tabaarakasmuka, wa ta\'aalaa jadduka, wa laa ilaaha ghayruk.',
    pronunciationBn: 'সুবহানাকা আল্লাহুম্মা ওয়া বিহামদিকা ওয়া তাবারাকাস মুকা ওয়া তাআলা জাদ্দুকা ওয়া লা ইলাহা গাইরুকা।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'Dua in Ruku (Bowing)',
    titleBn: 'রুকুর দোয়া',
    arabic: 'سُبْحَانَ رَبِّيَ الْعَظِيمِ',
    translationEn: 'Glory be to my Lord, the Almighty (three times).',
    translationBn: 'আমার মহান প্রতিপালকের পবিত্রতা ঘোষণা করছি (তিন বার)।',
    pronunciationEn: 'Subhaana Rabbiyal-\'Adheem.',
    pronunciationBn: 'সুবহানা রাব্বিয়াল আজীম।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'Rising from Ruku',
    titleBn: 'রুকু থেকে ওঠার দোয়া',
    arabic: 'سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ، رَبَّنَا وَلَكَ الْحَمْدُ',
    translationEn: 'Allah hears whoever praises Him. Our Lord, and to You belongs all praise.',
    translationBn: 'আল্লাহ শুনলেন যে তাঁর প্রশংসা করল। হে আমাদের রব, সমস্ত প্রশংসা আপনারই।',
    pronunciationEn: 'Sami\'a Allaahu liman hamidah, Rabbanaa wa lakal-hamd.',
    pronunciationBn: 'সামিয়াল্লাহু লিমান হামিদাহ, রাব্বানা ওয়া লাকাল হামদ।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'Dua in Sujud (Prostration)',
    titleBn: 'সিজদার দোয়া',
    arabic: 'سُبْحَانَ رَبِّيَ الْأَعْلَى',
    translationEn: 'Glory be to my Lord, the Most High (three times).',
    translationBn: 'আমার সর্বউচ্চ প্রতিপালকের পবিত্রতা ঘোষণা করছি (তিন বার)।',
    pronunciationEn: 'Subhaana Rabbiyal-A\'laa.',
    pronunciationBn: 'সুবহানা রাব্বিয়াল আলা।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'Sitting Between Sujuds',
    titleBn: 'দুই সিজদার মাঝের দোয়া',
    arabic: 'رَبِّ اغْفِرْ لِي، رَبِّ اغْفِرْ لِي',
    translationEn: 'My Lord forgive me, My Lord forgive me.',
    translationBn: 'হে আমার প্রতিপালক! আমাকে ক্ষমা করুন, হে আমার প্রতিপালক! আমাকে ক্ষমা করুন।',
    pronunciationEn: 'Rabbighfir lee, Rabbighfir lee.',
    pronunciationBn: 'রাব্বিগফির লী, রাব্বিগফির লী।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'Tashahhud (Sitting)',
    titleBn: 'তাশাহহুদ',
    arabic: 'التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ',
    translationEn: 'All compliments, prayers and pure words are due to Allah. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous slaves of Allah.',
    translationBn: 'সমস্ত মৌখিক, শারীরিক ও আর্থিক ইবাদত আল্লাহর জন্য। হে নবী, আপনার ওপর শান্তি, আল্লাহর রহমত ও বরকত বর্ষিত হোক। আমাদের ওপর এবং আল্লাহর নেক বান্দাদের ওপর শান্তি বর্ষিত হোক।',
    pronunciationEn: 'Attahiyyaatu lillaahi was-salawaatu wat-tayyibaatu, as-salaamu \'alayka ayyuhan-Nabiyyu wa rahmatullaahi wa barakaatuhu, as-salaamu \'alaynaa wa \'alaa \'ibaadillaahis-saaliheen.',
    pronunciationBn: 'আত্তাহিয়্যাতু লিল্লাহি ওয়াসসালাওয়াতু ওয়াত্তায়্যিবাতু, আসসালামু আলাইকা আইয়্যুহান নাবিয়্যু ওয়া রাহমাতুল্লাহি ওয়া বারাকাতুহু, আসসালামু আলাইনা ওয়া আলা ইবাদিল্লাহিস সালিহীন।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'Darood-e-Ibrahim',
    titleBn: 'দরুদে ইবরাহিম',
    arabic: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلِّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ',
    translationEn: 'O Allah, bestow Your favor upon Muhammad and upon the family of Muhammad, as You bestowed favor upon Ibrahim and upon the family of Ibrahim. Verily, You are Praiseworthy, Most Glorious.',
    translationBn: 'হে আল্লাহ! আপনি মুহাম্মদ ও তাঁর বংশধরদের ওপর রহমত বর্ষণ করুন, যেমন রহমত বর্ষণ করেছেন ইব্রাহিম ও তাঁর বংশধরদের ওপর। নিশ্চয়ই আপনি প্রশংসিত ও মহিমান্বিত।',
    pronunciationEn: 'Allahumma salli \'ala Muhammadin wa \'ala aali Muhammadin, kama sallayta \'ala Ibraheema wa \'ala aali Ibraheema, innaka Hameedun Majeed.',
    pronunciationBn: 'আল্লাহুম্মা সাল্লি আলা মুহাম্মাদিও ওয়া আলা আলি মুহাম্মদ, কামা সাল্লাইতা আলা ইব্রাহিমা ওয়া আলা আলি ইব্রাহিমা ইন্নাকা হামিদুম মাজিদ।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'Dua Qunut (Witr)',
    titleBn: 'কুনুতের দোয়া',
    arabic: 'اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ، وَعَافِنِي فِيمَنْ عَافَيْتَ، وَتَوَلَّني فِيمَنْ تَوَلَّيْتَ',
    translationEn: 'O Allah, guide me among those whom You have guided, and pardon me among those whom You have pardoned, and turn to me in friendship among those on whom You have turned.',
    translationBn: 'হে আল্লাহ! আপনি যাদের হেদায়েত করেছেন আমাকে তাদের অন্তর্ভুক্ত করুন, যাদের সুস্থতা দান করেছেন আমাকে তাদের অন্তর্ভুক্ত করুন, যাদের অভিভাবকত্ব গ্রহণ করেছেন আমাকে তাদের অন্তর্ভুক্ত করুন।',
    pronunciationEn: 'Allahumma-hdinee feeman hadayt, wa \'aafinee feeman \'aafayt, wa tawallanee feeman tawallayt.',
    pronunciationBn: 'আল্লাহুম্মাহদিনী ফীমান হাদাইত, ওয়া আফিনী ফীমান আফাইত, ওয়া তাওয়াল্লানী ফীমান তাওয়াল্লাইত।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'Dhikr After Tasleem',
    titleBn: 'সালাম ফিরানোর পরের যিকির',
    arabic: 'أَسْتَغْفِرُ اللَّهَ (ثَلَاثًا) اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ',
    translationEn: 'I ask Allah for forgiveness (three times). O Allah, You are As-Salam and from You is all peace, blessed are You, O Owner of majesty and honor.',
    translationBn: 'আমি আল্লাহর কাছে ক্ষমা প্রার্থনা করছি (৩ বার)। হে আল্লাহ! আপনিই শান্তি এবং আপনার পক্ষ থেকেই শান্তি আসে, আপনি বরকতময়, হে মহিমান্বিত ও মহানুভব।',
    pronunciationEn: 'Astaghfirullaah (x3). Allahumma Antas-Salaamu wa minkas-salaam, tabaarakta yaa Dhal-Jalaali wal-Ikraam.',
    pronunciationBn: 'আস্তাগফিরুল্লাহ (৩ বার)। আল্লাহুম্মা আনতাস সালামু ওয়া মিনকাস সালামু তাবারাকতা ইয়া জাল জালালি ওয়াল ইকরম।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),
  DuaItem(
    titleEn: 'Dua for Istikhara',
    titleBn: 'ইস্তিখারার দোয়া',
    arabic: 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ',
    translationEn: 'O Allah, I seek Your guidance [in making a choice] by virtue of Your knowledge, and I seek ability by virtue of Your power, and I ask You of Your great bounty.',
    translationBn: 'হে আল্লাহ! আমি আপনার জ্ঞানের সাহায্যে আপনার কাছে কল্যাণ প্রার্থনা করছি এবং আপনার কুদরতের সাহায্যে সক্ষমতা ও মহান অনুগ্রহ প্রার্থনা করছি।',
    pronunciationEn: 'Allahumma innee astakheeruka bi\'ilmika wa astaqdiruka biqudratika wa as\'aluka min fadlikal-\'adheem.',
    pronunciationBn: 'আল্লাহুম্মা ইন্নি আসতাখিরুকা বি ইলমিকা ওয়া আসতাকদিরুকা বিকুদরাতিকা ওয়া আসআলুকা মিন ফাদলিকাল আজিম।',
    categoryEn: 'Ablution & Prayer',
    categoryBn: 'ওযু ও নামাজ',
  ),

  // ── 5. Food / খাবার ─────────────────────────────────────────────────────
  DuaItem(
    titleEn: 'Before Eating',
    titleBn: 'খাবার শুরু করার দোয়া',
    arabic: 'بِسْمِ اللَّهِ',
    translationEn: 'In the name of Allah.',
    translationBn: 'আল্লাহর নামে (শুরু করছি)।',
    pronunciationEn: 'Bismillah.',
    pronunciationBn: 'বিসমিল্লাহ।',
    categoryEn: 'Food',
    categoryBn: 'খাবার',
  ),
  DuaItem(
    titleEn: 'After Eating',
    titleBn: 'খাবার শেষে দোয়া',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
    translationEn: 'Praise be to Allah Who has fed us and given us drink, and made us Muslims.',
    translationBn: 'সব প্রশংসা আল্লাহর জন্য, যিনি আমাদের খাইয়েছেন, পান করিয়েছেন এবং মুসলিম বানিয়েছেন।',
    pronunciationEn: 'Alhamdulillahilladhee at\'amanaa wa saqaanaa wa ja\'alanaa muslimeen.',
    pronunciationBn: 'আলহামদু লিল্লাহিল্লাজী আতআমানা ওয়া সাকানা ওয়া জাআালানা মুসলিমীন।',
    categoryEn: 'Food',
    categoryBn: 'খাবার',
  ),
  DuaItem(
    titleEn: 'Dua for Drinking Milk',
    titleBn: 'দুধ পান করার দোয়া',
    arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَزِدْنَا مِنْهُ',
    translationEn: 'O Allah, bless it for us and give us more of it.',
    translationBn: 'হে আল্লাহ! এতে আমাদের জন্য বরকত দান করুন এবং তা আরো বাড়িয়ে দিন।',
    pronunciationEn: 'Allahumma baarik lanaa feehi wa zidnaa minhu.',
    pronunciationBn: 'আল্লাহুম্মা বারিক লানা ফীহি ওয়া জিদনা মিনহু।',
    categoryEn: 'Food',
    categoryBn: 'খাবার',
  ),
  DuaItem(
    titleEn: 'Dua for Breaking Fast (Iftar)',
    titleBn: 'রোজা ইফতারের দোয়া',
    arabic: 'ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ',
    translationEn: 'The thirst is gone, the veins are moistened, and the reward is confirmed, if Allah wills.',
    translationBn: 'পিপাসা দূর হয়েছে, শিরা উপশিরা সিক্ত হয়েছে এবং আল্লাহর ইচ্ছায় পুরস্কারও নির্ধারিত হয়েছে।',
    pronunciationEn: 'Dhahaba-dhama\'u wabtallatil-\'urooqu wa thabatal-ajru in shaa\'a Allaah.',
    pronunciationBn: 'জাহাবাজ জামাউ ওয়াবতাল্লাতিল উরুকু ওয়া ছাবাতাল আজরু ইনশাআল্লাহ।',
    categoryEn: 'Food',
    categoryBn: 'খাবার',
  ),
  DuaItem(
    titleEn: 'Intention for Sahri',
    titleBn: 'সাহরির নিয়ত',
    arabic: 'وَبِصَوْمِ غَدٍ نَّوَيْتُ مِنْ شَهْرِ رَمَضَانَ',
    translationEn: 'I intend to fast tomorrow in the month of Ramadan (Note: Intention is of the heart).',
    translationBn: 'আমি আগামীকাল রমজান মাসের রোজা রাখার নিয়ত (সংকল্প) করছি।',
    pronunciationEn: 'Wa bisawmi ghadin nawaytu min shahri ramadaan.',
    pronunciationBn: 'ওয়া বিসাওমি গাদিন নাওয়াইতু মিন শাহরি রামাদান।',
    categoryEn: 'Food',
    categoryBn: 'খাবার',
  ),

  // ── 6. Clothing / পোশাক ──────────────────────────────────────────────────
  DuaItem(
    titleEn: 'Dua for Wearing Clothes',
    titleBn: 'কাপড় পরার দোয়া',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا الثَّوْبَ وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
    translationEn: 'Praise be to Allah who has clothed me with this garment and provided it for me without any might or power from myself.',
    translationBn: 'সমস্ত প্রশংসা আল্লাহর জন্য যিনি আমাকে এই পোশাকটি পরিয়েছেন এবং এটি আমাকে দান করেছেন আমার নিজের কোনো চেষ্টা ও ক্ষমতা ছাড়া।',
    pronunciationEn: 'Alhamdu lillaahil-ladhee kasaanee haadhadh-thawba wa razaqaneehi min ghayri hawlin minnee wa laa quwwah.',
    pronunciationBn: 'আলহামদু লিল্লাহিল্লাজী কাসানী হাজাছ ছাওবা ওয়া রাজাকানীহি মিন গাইরি হাওলিম মিন্নী ওয়ালা কুয়্যাহ।',
    categoryEn: 'Clothing',
    categoryBn: 'পোশাক',
  ),
  DuaItem(
    titleEn: 'Wearing New Clothes',
    titleBn: 'নতুন কাপড় পরার দোয়া',
    arabic: 'اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ كَسَوْتَنِيهِ، أَسْأَلُكَ مِنْ خَيْرِهِ وَخَيْرِ مَا صُنِعَ لَهُ',
    translationEn: 'O Allah, praise is to You. You have clothed me with it. I ask You for its goodness and the goodness of what it was made for.',
    translationBn: 'হে আল্লাহ! আপনার জন্যই সমস্ত প্রশংসা, আপনি আমাকে এটি পরিয়েছেন। আমি আপনার কাছে এর কল্যাণ ও যে কাজের জন্য এটি তৈরি করা হয়েছে তার কল্যাণ প্রার্থনা করছি।',
    pronunciationEn: 'Allahumma lakal-hamdu Anta kasawtaneehi, as\'aluka min khayrihi wa khayri maa suni\'a lahu.',
    pronunciationBn: 'আল্লাহুম্মা লাকাল হামদু আনতা কাসাওতানিহি, আসআলুকা মিন খাইরিহি ওয়া খাইরি মা সুনিআ লাহু।',
    categoryEn: 'Clothing',
    categoryBn: 'পোশাক',
  ),
  DuaItem(
    titleEn: 'Dua for Undressing',
    titleBn: 'কাপড় খোলার দোয়া',
    arabic: 'بِسْمِ اللَّهِ',
    translationEn: 'In the name of Allah (veils the eyes of Jinn).',
    translationBn: 'আল্লাহর নামে (যা জিনদের দৃষ্টি থেকে পর্দা স্বরূপ)।',
    pronunciationEn: 'Bismillah.',
    pronunciationBn: 'বিসমিল্লাহ।',
    categoryEn: 'Clothing',
    categoryBn: 'পোশাক',
  ),
  DuaItem(
    titleEn: 'Dua When Looking in Mirror',
    titleBn: 'আয়নায় নিজেকে দেখে দোয়া',
    arabic: 'اللَّهُمَّ كَمَا حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي',
    translationEn: 'O Allah, as You have made my appearance beautiful, make my character beautiful.',
    translationBn: 'হে আল্লাহ! আপনি যেভাবে আমার শরীর ও চেহারা সুন্দর করেছেন, সেভাবে আমার চরিত্রও সুন্দর করে দিন।',
    pronunciationEn: 'Allahumma kamaa hassanta khalqee fahassin khuluqee.',
    pronunciationBn: 'আল্লাহুম্মা কামা হাস্সান্তা খালকী ফাহাসসিন খুলুকী।',
    categoryEn: 'Clothing',
    categoryBn: 'পোশাক',
  ),

  // ── 7. Travel / ভ্রমণ ────────────────────────────────────────────────────
  DuaItem(
    titleEn: 'Dua for Travel (Safar)',
    titleBn: 'সফরের দোয়া',
    arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
    translationEn: 'Glory to Him Who has brought this [vehicle] under our control, though we could not have done it ourselves. And indeed, to our Lord we will surely return.',
    translationBn: 'পবিত্র মহান সেই সত্তা, যিনি এটিকে আমাদের জন্য বশীভূত করেছেন অথচ আমরা একে বশীভূত করতে সমর্থ ছিলাম না। আর নিশ্চয়ই আমরা আমাদের প্রতিপালকের দিকে প্রত্যাবর্তনকারী।',
    pronunciationEn: 'Subhaanalladhee sakhkhara lanaa haadhaa wa maa kunnaa lahu muqrineen, wa innaa ilaa Rabbinaa lamunqaliboon.',
    pronunciationBn: 'সুবহানাল্লাজী সাখখারা লানা হাজা ওয়ামা কুন্না লাহু মুকরিনীন, ওয়া ইন্না ইলা রাব্বিনা লামুনকালিবুন।',
    categoryEn: 'Travel',
    categoryBn: 'ভ্রমণ',
  ),
  DuaItem(
    titleEn: 'Mounting the Vehicle',
    titleBn: 'বাহনে ওঠার দোয়া',
    arabic: 'بِسْمِ اللَّهِ، الْحَمْدُ لِلَّهِ، اللَّهُ أَكْبَرُ',
    translationEn: 'In the name of Allah, praise be to Allah, Allah is the Greatest.',
    translationBn: 'আল্লাহর নামে, সমস্ত প্রশংসা আল্লাহর জন্য, আল্লাহ সর্বশ্রেষ্ঠ।',
    pronunciationEn: 'Bismillah, Alhamdulillah, Allahu Akbar.',
    pronunciationBn: 'বিসমিল্লাহ, আলহামদুলিল্লাহ, আল্লাহু আকবার।',
    categoryEn: 'Travel',
    categoryBn: 'ভ্রমণ',
  ),
  DuaItem(
    titleEn: 'Returning from Travel',
    titleBn: 'সফর থেকে ফেরার দোয়া',
    arabic: 'آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ',
    translationEn: 'We return, repenting, worshipping, and praising our Lord.',
    translationBn: 'আমরা প্রত্যাবর্তন করছি তওবাকারী, ইবাদতকারী এবং আমাদের রবের প্রশংসাকারী হিসেবে।',
    pronunciationEn: 'Aa\'iboona taa\'iboona \'aabidoona liRabbinaa haamidoon.',
    pronunciationBn: 'আইবুনা তাইবুনা আবিদুনা লিরব্বিনা হামিদুন।',
    categoryEn: 'Travel',
    categoryBn: 'ভ্রমণ',
  ),
  DuaItem(
    titleEn: 'Entering a City or Town',
    titleBn: 'কোনো শহরে প্রবেশের দোয়া',
    arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِيهَا',
    translationEn: 'O Allah, bless us in it.',
    translationBn: 'হে আল্লাহ! আমাদের জন্য এই শহরে বরকত দান করুন।',
    pronunciationEn: 'Allahumma baarik lanaa feehaa.',
    pronunciationBn: 'আল্লাহুম্মা বারিক লানা ফীহা।',
    categoryEn: 'Travel',
    categoryBn: 'ভ্রমণ',
  ),

  // ── 8. Family / পরিবার ───────────────────────────────────────────────────
  DuaItem(
    titleEn: 'Dua Before Marital Relations',
    titleBn: 'স্বামী-স্ত্রীর মিলনের দোয়া',
    arabic: 'اللَّهُمَّ جَنِّبْنَا الشَّيْطَانَ وَجَنِّبِ الشَّيْطَانَ مَا رَزَقْتَنَا',
    translationEn: 'O Allah, keep Satan away from us and keep Satan away from what You bestow upon us.',
    translationBn: 'হে আল্লাহ! আপনি আমাদের শয়তান থেকে দূরে রাখুন এবং আমাদের যে সন্তান দান করবেন তাকেও শয়তান থেকে রক্ষা করুন।',
    pronunciationEn: 'Allahumma jannibnash-shaytaana wa jannibish-shaytaana maa razaqtanaa.',
    pronunciationBn: 'আল্লাহুম্মা জান্নিবনাশ শায়তানা ওয়া জান্নিবিশ শায়তানা মা রাজাকতানা।',
    categoryEn: 'Family',
    categoryBn: 'পরিবার',
  ),
  DuaItem(
    titleEn: 'Dua for Having Children',
    titleBn: 'সন্তান লাভের দোয়া',
    arabic: 'رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ',
    translationEn: 'My Lord, grant me [a child] from among the righteous.',
    translationBn: 'হে আমার প্রতিপালক! আমাকে এক সৎকর্মশীল সন্তান দান করুন।',
    pronunciationEn: 'Rabbi hab lee minas-saaliheen.',
    pronunciationBn: 'রাব্বি হাব লী মিনাস সালিহীন।',
    categoryEn: 'Family',
    categoryBn: 'পরিবার',
  ),
  DuaItem(
    titleEn: 'Protection for Children',
    titleBn: 'সন্তানদের জন্য দোয়া',
    arabic: 'أُعِيذُكُمَا بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ',
    translationEn: 'I seek refuge for you in the perfect words of Allah from every devil, poisonous pest and every evil eye.',
    translationBn: 'আমি তোমাদের জন্য আল্লাহর পরিপূর্ণ বাণীর আশ্রয়ে প্রার্থনা করছি সমস্ত শয়তান, ক্ষতিকর কীট এবং বদনজর থেকে।',
    pronunciationEn: 'U\'eedhukumaa bikalimaati-llaahit-taammati min kulli shaytaanin wa haammatin, wa min kulli \'aynin laammah.',
    pronunciationBn: 'উইজুকা বিকালি মাতিল্লাহিত তাম্মাতি মিন কুল্লি শায়তানিও ওয়া হাম্মাহ ওয়া মিন কুল্লি আইনিন লাম্মাহ।',
    categoryEn: 'Family',
    categoryBn: 'পরিবার',
  ),
  DuaItem(
    titleEn: 'Dua for Parents',
    titleBn: 'পিতা-মাতার জন্য দোয়া',
    arabic: 'رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    translationEn: 'My Lord, have mercy upon them as they brought me up [when I was] small.',
    translationBn: 'হে আমার প্রতিপালক! তাদের প্রতি দয়া করো যেভাবে তারা শৈশবে আমাকে প্রতিপালন করেছিলেন।',
    pronunciationEn: 'Rabbir-hamhumaa kamaa rabbayaanee sagheeraa.',
    pronunciationBn: 'রাব্বির হামহুমা কামা রাব্বাইয়ানি সাগীরা।',
    categoryEn: 'Family',
    categoryBn: 'পরিবার',
  ),
  DuaItem(
    titleEn: 'Dua for Family Well-being',
    titleBn: 'পরিবারের জন্য দোয়া',
    arabic: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا',
    translationEn: 'Our Lord, grant us from among our wives and offspring comfort to our eyes and make us an example for the righteous.',
    translationBn: 'হে আমাদের প্রতিপালক! আমাদের স্ত্রীদের ও সন্তানদের আমাদের জন্য চোখের শীতলতা স্বরূপ বানিয়ে দিন এবং আমাদের মুত্তাকিদের ইমাম বানিয়ে দিন।',
    pronunciationEn: 'Rabbanaa hab lanaa min azwaajinaa wa dhurriyyaatinaa qurrata a\'yunin waj\'alnaa lilmuttaqeena imaamaa.',
    pronunciationBn: 'রাব্বানা হাব লানা মিন আজওয়াজিনা ওয়া জুররিয়্যাতিনা কুররাতা আইয়ুনিও ওয়াজআলনা লিল মুত্তাকীনা ইমামা।',
    categoryEn: 'Family',
    categoryBn: 'পরিবার',
  ),

  // ── 9. Morning & Evening / সকাল-সন্ধ্যার আমল ───────────────────────────────
  DuaItem(
    titleEn: 'Morning Dua',
    titleBn: 'সকালবেলার দোয়া',
    arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
    translationEn: 'O Allah, by You we enter the morning, by You we enter the evening, by You we live, by You we die, and to You is the resurrection.',
    translationBn: 'হে আল্লাহ! আপনার অনুগ্রহে আমরা সকালে উপনীত হয়েছি, আপনার অনুগ্রহে সন্ধ্যায় উপনীত হয়েছি, আপনার অনুগ্রহে জীবিত আছি এবং আপনার অনুগ্রহেই আমরা মৃত্যুবরণ করব, আর আপনার নিকটই আমাদের ফিরে যেতে হবে।',
    pronunciationEn: 'Allahumma bika asbahnaa, wa bika amsaynaa, wa bika nahyaa, wa bika namootu, wa ilaykin-nushoor.',
    pronunciationBn: 'আল্লাহুম্মা বিকা আসবাহনা, ওয়া বিকা আমসাইনা, ওয়া বিকা নাহয়া, ওয়া বিকা নামূতু, ওয়া ইলাইহিন নুশূর।',
    categoryEn: 'Morning & Evening',
    categoryBn: 'সকাল-সন্ধ্যার আমল',
  ),
  DuaItem(
    titleEn: 'Evening Dua',
    titleBn: 'সন্ধ্যাবেলার দোয়া',
    arabic: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ',
    translationEn: 'O Allah, by You we enter the evening, by You we enter the morning, by You we live, by You we die, and to You is the final return.',
    translationBn: 'হে আল্লাহ! আপনার অনুগ্রহে আমরা সন্ধ্যায় উপনীত হয়েছি, আপনার অনুগ্রহে সকালে উপনীত হয়েছি, আপনার অনুগ্রহে জীবিত আছি এবং আপনার অনুগ্রহেই আমরা মৃত্যুবরণ করব, আর আপনার নিকটই আমাদের ফিরে যেতে হবে।',
    pronunciationEn: 'Allahumma bika amsaynaa, wa bika asbahnaa, wa bika nahyaa, wa bika namootu, wa ilaykil-maseer.',
    pronunciationBn: 'আল্লাহুম্মা বিকা আমসাইনা, ওয়া বিকা আসবাহনা, ওয়া বিকা নাহয়া, ওয়া বিকা নামূতু, ওয়া ইলাইখিল মাছীর।',
    categoryEn: 'Morning & Evening',
    categoryBn: 'সকাল-সন্ধ্যার আমল',
  ),
  DuaItem(
    titleEn: 'The Three Quls',
    titleBn: 'তিন কুল (ইখলাস, ফালাক ও নাস)',
    arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ... قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ... قُلْ أَعُوذُ بِرَبِّ النَّاسِ',
    translationEn: 'Recite Surah Al-Ikhlas, Surah Al-Falaq, and Surah An-Nas (3 times each in morning and evening for complete protection).',
    translationBn: 'সূরা ইখলাস, সূরা ফালাক এবং সূরা নাস (সকাল-সন্ধ্যায় ৩ বার করে পাঠ করুন যা সব অনিষ্ট থেকে সুরক্ষার জন্য যথেষ্ট)।',
    pronunciationEn: 'Surah Al-Ikhlas, Al-Falaq, An-Nas.',
    pronunciationBn: 'সূরা আল-ইখলাস, আল-ফালাক, আন-নাস।',
    categoryEn: 'Morning & Evening',
    categoryBn: 'সকাল-সন্ধ্যার আমল',
  ),
  DuaItem(
    titleEn: 'Ayat al-Kursi',
    titleBn: 'আয়াতুল কুরসি',
    arabic: 'اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ...',
    translationEn: 'Allah! There is no deity except Him, the Ever-Living, the Sustainer of all existence...',
    translationBn: 'আল্লাহ ছাড়া কোনো সত্য ইলাহ নেই, তিনি চিরঞ্জীব, সর্বসত্তার ধারক... (সকাল-সন্ধ্যায় এবং প্রতি ফরজ নামাজের পর পাঠের অপরিসীম গুরুত্ব রয়েছে)।',
    pronunciationEn: 'Allahu laa ilaaha illaa Huwal-Hayyul-Qayyoom, laa ta\'khudhuhu sinatun wa laa nawm...',
    pronunciationBn: 'আল্লাহু লা ইলাহা ইল্লা হুয়াল হাইয়্যুল কাইয়্যুম, লা তা’খুজুহু সিনাতুও ওয়ালা নাউম...',
    categoryEn: 'Morning & Evening',
    categoryBn: 'সকাল-সন্ধ্যার আমল',
  ),
  DuaItem(
    titleEn: 'Sayyidul Istighfar',
    titleBn: 'সাইয়্যিদুল ইস্তিগফার',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ ...',
    translationEn: 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I am faithful to my covenant and my promise as much as I can...',
    translationBn: 'হে আল্লাহ! আপনি আমার প্রতিপালক। আপনি ছাড়া কোনো সত্য ইলাহ নেই। আপনি আমাকে সৃষ্টি করেছেন এবং আমি আপনার বান্দা। আর আমি সাধ্যমতো আপনার অঙ্গীকার ও প্রতিশ্রুতির ওপর কায়েম আছি...',
    pronunciationEn: 'Allahumma Anta Rabbee laa ilaaha illaa Ant, khalaqtanee wa ana \'abduk, wa ana \'alaa \'ahdika wa wa\'dika mas-tata\'t...',
    pronunciationBn: 'আল্লাহুম্মা আনতা রাব্বী লা ইলাহা ইল্লা আনতা, খালাকতানি ওয়া আনা আবদুকা, ওয়া আনা আলা আহদিকা ওয়া ওয়াদিকা মাসতাতাতু...',
    categoryEn: 'Morning & Evening',
    categoryBn: 'সকাল-সন্ধ্যার আমল',
  ),

  // ── 10. Forgiveness & Repentance / ক্ষমা ও তাওবা ──────────────────────────
  DuaItem(
    titleEn: 'Daily Istighfar',
    titleBn: 'ইস্তিগফারের দোয়া',
    arabic: 'أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ',
    translationEn: 'I seek the forgiveness of Allah and turn to Him in repentance.',
    translationBn: 'আমি আল্লাহর কাছে ক্ষমা প্রার্থনা করছি এবং তাঁর নিকট তাওবা করছি (ফিরে যাচ্ছি)।',
    pronunciationEn: 'Astaghfirullaaha wa atoobu ilayh.',
    pronunciationBn: 'আস্তাগফিরুল্লাহ ওয়া আতূবু ইলাইহি।',
    categoryEn: 'Forgiveness',
    categoryBn: 'ক্ষমা ও তাওবা',
  ),
  DuaItem(
    titleEn: 'Dua for Repentance (Tawbah)',
    titleBn: 'তাওবার দোয়া',
    arabic: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ',
    translationEn: 'My Lord, forgive and have mercy, and You are the best of the merciful.',
    translationBn: 'হে আমার প্রতিপালক! আমাকে ক্ষমা করুন ও দয়া করুন, আর আপনিই সর্বশ্রেষ্ঠ দয়ালু।',
    pronunciationEn: 'Rabbigh-fir warham wa Anta khayrur-raahimeen.',
    pronunciationBn: 'রাব্বিগফির ওয়ারহাম ওয়া আনতা খাইরুর রাহিমীন।',
    categoryEn: 'Forgiveness',
    categoryBn: 'ক্ষমা ও তাওবা',
  ),
  DuaItem(
    titleEn: 'Forgiveness of Sins',
    titleBn: 'গুনাহ মাফের দোয়া',
    arabic: 'رَبَّنَا ظَلَمْنَا أَنْفُسَنَا وَإِنْ لَمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ',
    translationEn: 'Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.',
    translationBn: 'হে আমাদের প্রতিপালক! আমরা নিজেদের ওপর জুলুম করেছি। আর আপনি যদি আমাদের ক্ষমা না করেন এবং দয়া না করেন, তবে আমরা অবশ্যই ক্ষতিগ্রস্তদের অন্তর্ভুক্ত হব।',
    pronunciationEn: 'Rabbanaa dhalamnaa anfusanaa wa in lam taghfir lanaa wa tarhamnaa lanakoonanna minal-khaasireen.',
    pronunciationBn: 'রাব্বানা জলামনা আনফুসানা ওয়া ইল্লাম তাগফির লানা ওয়া তারহামনা লানাকুনান্না মিনাল খাসিরীন।',
    categoryEn: 'Forgiveness',
    categoryBn: 'ক্ষমা ও তাওবা',
  ),

  // ── 11. Hardship & Danger / বিপদ-আপদ ───────────────────────────────────
  DuaItem(
    titleEn: 'Relief from Anxiety and Sorrow',
    titleBn: 'দুশ্চিন্তা ও দুঃখ মুক্তির দোয়া',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ',
    translationEn: 'O Allah, I seek refuge in You from worry and grief, incapacity and laziness, miserliness and cowardice, the burden of debt and being overpowered by men.',
    translationBn: 'হে আল্লাহ! আমি আপনার নিকট আশ্রয় চাচ্ছি দুশ্চিন্তা ও দুঃখ-বেদনা থেকে, অক্ষমতা ও অলসতা থেকে, কৃপণতা ও ভীরুতা থেকে এবং ঋণের বোঝা ও মানুষের দমন-পীড়ন থেকে।',
    pronunciationEn: 'Allahumma innee a\'udhu bika minal-hammi wal-hazani, wal-\'ajzi wal-kasali, wal-bukhli wal-jubni, wa dala\'id-dayni wa ghalabatir-rijaal.',
    pronunciationBn: 'আল্লাহুম্মা ইন্নি আউজু বিকা মিনাল হাম্মি ওয়াল হুযনি, ওয়াল আজযি ওয়াল কাসালি, ওয়াল বুখলি ওয়াল জুবনি, ওয়া দ্বালাইদ দাইনি ওয়া গালাবাতির রিজাল।',
    categoryEn: 'Hardship & Danger',
    categoryBn: 'বিপদ-আপদ',
  ),
  DuaItem(
    titleEn: 'Dua During Distress / Hardship',
    titleBn: 'কষ্টের সময় দোয়া',
    arabic: 'إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ، اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا',
    translationEn: 'Indeed, we belong to Allah, and indeed to Him we will return. O Allah, reward me in my affliction and replace it with something better.',
    translationBn: 'আমরা তো আল্লাহরই এবং নিশ্চয়ই আমরা তাঁরই দিকে প্রত্যাবর্তনকারী। হে আল্লাহ! আমাকে আমার এই বিপদে প্রতিদান দিন এবং এর চেয়ে উত্তম কিছু দান করুন।',
    pronunciationEn: 'Innaa lillaahi wa innaa ilayhi raaji\'oon, Allahumma\'jurnee fee museebatee wa akhlif lee khayran minhaa.',
    pronunciationBn: 'ইন্না লিল্লাহি ওয়া ইন্না ইলাইহি রাজিউন, আল্লাহুম্মাজুরনী ফী মুসীবাতী ওয়া আখলিফ লী খাইরাম মিনহা।',
    categoryEn: 'Hardship & Danger',
    categoryBn: 'বিপদ-আপদ',
  ),
  DuaItem(
    titleEn: 'Dua for Freedom from Debt',
    titleBn: 'ঋণমুক্তির দোয়া',
    arabic: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ، وَأَغْنِنَا بِفَضْلِكَ عَمَّنْ سِوَاكَ',
    translationEn: 'O Allah, suffice me with Your lawful things instead of Your unlawful things, and make me independent of all others besides You.',
    translationBn: 'হে আল্লাহ! আপনি আমাকে আপনার হালাল রিজিক দিয়ে সন্তুষ্ট রাখুন হারাম থেকে দূরে রেখে এবং আপনার অনুগ্রহে আপনি ছাড়া অন্য সবার মুখাপেক্ষীহীন করে দিন।',
    pronunciationEn: 'Allahummak-finee bihalaalika \'an haraamika, wa aghninee bifadlika \'amman siwaaka.',
    pronunciationBn: 'আল্লাহুম্মাক ফিনী বিহালালিকা আন হারামিকা, ওয়া আগনিনী বিফাদলিকা আম্মান সিওয়াকা।',
    categoryEn: 'Hardship & Danger',
    categoryBn: 'বিপদ-আপদ',
  ),
  DuaItem(
    titleEn: 'Dua for Cure and Relief',
    titleBn: 'রোগমুক্তির দোয়া',
    arabic: 'أَذْهِبِ الْبَأْسَ رَبَّ النَّاسِ، وَاشْفِ أَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا',
    translationEn: 'Remove the disease, O Lord of the people, and cure, for You are the Curer. There is no cure but Your cure, a cure that leaves no illness.',
    translationBn: 'হে মানুষের প্রতিপালক! কষ্ট দূর করে দিন এবং আরোগ্য দান করুন, আপনিই আরোগ্যদানকারী। আপনার আরোগ্য ছাড়া কোনো আরোগ্য নেই, এমন আরোগ্য যা কোনো রোগ অবশিষ্ট রাখে না।',
    pronunciationEn: 'Adhhibil-ba\'sa Rabban-naasi, washfi Antash-Shaafee, laa shifaa\'a illaa shifaa\'uka, shifaa\'an laa yughaadiru saqamaa.',
    pronunciationBn: 'আজহিবিল বা’সা রাব্বান নাসি, ওয়াশফি আনতাশ শাফী, লা শিফাআ ইল্লা শিফাউকা শিফাআল লা ইউগাদিরু সাকামা।',
    categoryEn: 'Hardship & Danger',
    categoryBn: 'বিপদ-আপদ',
  ),
  DuaItem(
    titleEn: 'Dua for Fever',
    titleBn: 'জ্বরের দোয়া',
    arabic: 'بِسْمِ اللَّهِ الْكَبِيرِ أَعُوذُ بِاللَّهِ الْعَظِيمِ مِنْ شَرِّ كُلِّ عِرْقٍ نَعَّارٍ وَمِنْ شَرِّ حَرِّ النَّارِ',
    translationEn: 'In the name of Allah the Great, I seek refuge in Allah the Almighty from the evil of every spurting vein and the evil heat of the Fire.',
    translationBn: 'মহান আল্লাহর নামে, আমি সর্বশক্তিমান আল্লাহর কাছে আশ্রয় চাই স্পন্দিত রগসমূহের অনিষ্ট থেকে এবং আগুনের উত্তাপের অনিষ্ট থেকে।',
    pronunciationEn: 'Bismillaahil-Kabeer a\'udhu billaahil-\'Adheemi min sharri kulli \'irqin na\'aarin wa min sharri harrin-Naar.',
    pronunciationBn: 'বিসমিল্লাহিল কাবীর আউজু বিল্লাহিল আজীমি মিন শাররি কুল্লি ইরকিন নাআরিন ওয়া মিন শাররি হাররিন নার।',
    categoryEn: 'Hardship & Danger',
    categoryBn: 'বিপদ-আপদ',
  ),
  DuaItem(
    titleEn: 'Seeking Refuge from Satan',
    titleBn: 'শয়তান থেকে আশ্রয়ের দোয়া',
    arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
    translationEn: 'I seek refuge in Allah from the accursed Satan.',
    translationBn: 'আমি বিতাড়িত শয়তান থেকে আল্লাহর নিকট আশ্রয় প্রার্থনা করছি।',
    pronunciationEn: 'A\'udhu billahi minash-shaytanir-rajim.',
    pronunciationBn: 'আউজু বিল্লাহি মিনাশ শাইতানির রাজিম।',
    categoryEn: 'Hardship & Danger',
    categoryBn: 'বিপদ-আপদ',
  ),
  DuaItem(
    titleEn: 'Dua in Fear',
    titleBn: 'ভয় লাগলে দোয়া',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ غَضَبِهِ وَعِقَابِهِ وَشَرِّ عِبَادِهِ وَمِنْ هَمَزَاتِ الشَّيَاطِينِ وَأَنْ يَحْضُرُونِ',
    translationEn: 'I seek refuge in the perfect words of Allah from His anger, His punishment, the evil of His servants, and from the evil suggestions of the devils and their presence.',
    translationBn: 'আমি আল্লাহর পরিপূর্ণ কালিমাসমূহের উসিলায় আশ্রয় চাই তাঁর ক্রোধ ও শাস্তি থেকে, তাঁর বান্দাদের অনিষ্ট থেকে এবং শয়তানদের কুমন্ত্রণা ও তাদের উপস্থিতি থেকে।',
    pronunciationEn: 'A\'udhu bi kalimaati-llaahit-taammaati min ghadabihi wa \'iqaabihi wa sharri \'ibaadihi wa min hamazaatish-shayaateeni wa an yahduroon.',
    pronunciationBn: 'আউজু বিকালি মাতিল্লাহিত তাম্মাতি মিন গাদাবিহি ওয়া ইকাবিহি ওয়া শাররি ইবাদিহি ওয়া মিন হামাযাতিশ শায়াতীনি ওয়া আই ইয়াহদুরুনি।',
    categoryEn: 'Hardship & Danger',
    categoryBn: 'বিপদ-আপদ',
  ),
  DuaItem(
    titleEn: 'Dua to Control Anger',
    titleBn: 'রাগ কমানোর দোয়া',
    arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
    translationEn: 'I seek refuge in Allah from the accursed Satan.',
    translationBn: 'আমি বিতাড়িত শয়তান থেকে আল্লাহর নিকট আশ্রয় প্রার্থনা করছি।',
    pronunciationEn: 'A\'udhu billahi minash-shaytanir-rajim.',
    pronunciationBn: 'আউজু বিল্লাহি মিনাশ শাইতানির রাজিম।',
    categoryEn: 'Hardship & Danger',
    categoryBn: 'বিপদ-আপদ',
  ),

  // ── 12. Rizq & Blessings / রিজিক ও বরকত ─────────────────────────────────
  DuaItem(
    titleEn: 'Dua for Halal Sustenance',
    titleBn: 'হালাল রিজিকের দোয়া',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا',
    translationEn: 'O Allah, I ask You for beneficial knowledge, good sustenance, and accepted deeds.',
    translationBn: 'হে আল্লাহ! আমি আপনার কাছে উপকারী জ্ঞান, পবিত্র ও হালাল রিজিক এবং কবুলযোগ্য আমল প্রার্থনা করছি।',
    pronunciationEn: 'Allahumma innee as\'aluka \'ilman naafi\'an, wa rizqan tayyiban, wa \'amalan mutaqabbalan.',
    pronunciationBn: 'আল্লাহুম্মা ইন্নি আসআলুকা ইলমান নাফিয়ান, ওয়া রিজকান তায়্যিবান, ওয়া আমালান মুতাকাব্বালান।',
    categoryEn: 'Rizq & Blessings',
    categoryBn: 'রিজিক ও বরকত',
  ),
  DuaItem(
    titleEn: 'Blessings in Business',
    titleBn: 'ব্যবসায় বরকতের দোয়া',
    arabic: 'اللَّهُمَّ بَارِكْ لَهُمْ فِي مِكْيَالِهِمْ، وَبَارِكْ لَهُمْ فِي صَاعِهِمْ وَمُدِّهِمْ',
    translationEn: 'O Allah, bless them in their measure, and bless them in their weight (for prosperity in trade).',
    translationBn: 'হে আল্লাহ! তাদের পরিমাপে বরকত দিন এবং তাদের ওজনে ও ব্যবসায়ের পণ্যে বরকত দিন।',
    pronunciationEn: 'Allahumma baarik lahum fee mikyaalihim, wa baarik lahum fee saa\'ihim wa muddihim.',
    pronunciationBn: 'আল্লাহুম্মা বারিক লাহুম ফী মিকয়ালিহিম ওয়া বারিক লাহুম ফী সায়িহিম ওয়া মুদ্দিহিম।',
    categoryEn: 'Rizq & Blessings',
    categoryBn: 'রিজিক ও বরকত',
  ),
  DuaItem(
    titleEn: 'Dua for Sufficiency and Wealth',
    titleBn: 'ধনী হওয়ার জন্য দোয়া',
    arabic: 'اللَّهُمَّ رَبَّ السَّمَاوَاتِ السَّبْعِ وَرَبَّ الْعَرْشِ الْعَظِيمِ، اقْضِ عَنَّا الدَّيْنَ وَأَغْنِنَا مِنَ الْفَقْرِ',
    translationEn: 'O Allah, Lord of the seven heavens and Lord of the Great Throne, clear our debts and free us from poverty.',
    translationBn: 'হে আল্লাহ, সাত আসমানের রব এবং মহান আরশের রব! আমাদের সমস্ত ঋণ পরিশোধ করে দিন এবং আমাদের অভাব দূর করে ধনী বানিয়ে দিন।',
    pronunciationEn: 'Allahumma Rabbas-samaawaatis-sab\'i wa Rabbal-\'Arshil-\'Adheem, iqdi \'annad-dayna wa aghninaa minal-faqr.',
    pronunciationBn: 'আল্লাহুম্মা রাব্বাস সামাওয়াতিস সাবয়ি ওয়া রাব্বাল আরশিল আজীম, ইকদ্বি আন্নাদ দাইনা ওয়া আগনিনা মিনাল ফাকর।',
    categoryEn: 'Rizq & Blessings',
    categoryBn: 'রিজিক ও বরকত',
  ),
  DuaItem(
    titleEn: 'Dua to Repay Debt',
    titleBn: 'ঋণ পরিশোধের দোয়া',
    arabic: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ',
    translationEn: 'O Allah, make the lawful sufficient for me over the unlawful.',
    translationBn: 'হে আল্লাহ! হারাম ব্যতিরেকে আপনার হালাল উপার্জন আমার জন্য যথেষ্ট করুন।',
    pronunciationEn: 'Allahummak-finee bihalaalika \'an haraamika.',
    pronunciationBn: 'আল্লাহুম্মাকফিনী বিহালালিকা আন হারামিকা।',
    categoryEn: 'Rizq & Blessings',
    categoryBn: 'রিজিক ও বরকত',
  ),

  // ── 13. Rain / বৃষ্টি ────────────────────────────────────────────────────
  DuaItem(
    titleEn: 'Dua Seeking Rain (Istisqa)',
    titleBn: 'বৃষ্টি চাওয়ার দোয়া',
    arabic: 'اللَّهُمَّ اسْقِنَا غَيْثًا مُغِيثًا مَرِيئًا مَرِيعًا نَافِعًا غَيْرَ ضَارٍّ',
    translationEn: 'O Allah, send us rain that is abundant, wholesome, productive, beneficial and not harmful.',
    translationBn: 'হে আল্লাহ! আমাদের ওপর এমন বৃষ্টি বর্ষণ করুন যা সাহায্যকারী, তৃপ্তিদায়ক, সতেজকারী, উপকারী ও ক্ষতিকর নয়।',
    pronunciationEn: 'Allahummas-qinaa ghaythan mugheethan maree\'an maree\'an naafi\'an ghayra daarr.',
    pronunciationBn: 'আল্লাহুম্মাসকিনা গাইসান মুগিসান মারীয়ান মারীয়ান নাফিয়ান গাইরা দারর।',
    categoryEn: 'Rain',
    categoryBn: 'বৃষ্টি',
  ),
  DuaItem(
    titleEn: 'Dua When it Rains',
    titleBn: 'বৃষ্টি হলে দোয়া',
    arabic: 'اللَّهُمَّ صَيِّبًا نَافِعًا',
    translationEn: 'O Allah, send upon us a beneficial rain.',
    translationBn: 'হে আল্লাহ! আমাদের ওপর উপকারী বৃষ্টি বর্ষণ করুন।',
    pronunciationEn: 'Allahumma sayyiban naafi\'an.',
    pronunciationBn: 'আল্লাহুম্মা সয়্যিবান নাফিয়ান।',
    categoryEn: 'Rain',
    categoryBn: 'বৃষ্টি',
  ),
  DuaItem(
    titleEn: 'Dua to Stop Heavy Rain',
    titleBn: 'অতিবৃষ্টি বন্ধের দোয়া',
    arabic: 'اللَّهُمَّ حَوَالَيْنَا وَلَا عَلَيْنَا، اللَّهُمَّ عَلَى الْآكَامِ وَالظِّرَابِ، وَبُطُونِ الْأَوْدِيَةِ',
    translationEn: 'O Allah, around us and not upon us. O Allah, upon the hills, mountains, and valleys.',
    translationBn: 'হে আল্লাহ! আমাদের আশেপাশে বর্ষণ করুন, আমাদের ওপর নয়। হে আল্লাহ! পাহাড়, পর্বত, টিলা এবং উপত্যকার মাঝে বর্ষণ করুন।',
    pronunciationEn: 'Allahumma hawaalaynaa wa laa \'alaynaa, Allahumma \'alal-aakaami wadh-dhiraabi, wa butoonil-awdiyah.',
    pronunciationBn: 'আল্লাহুম্মা হাওয়ালাইনা ওয়ালা আলাইনা, আল্লাহুম্মা আলাল আকামি ওয়াজ জিরাবি ওয়া বুতুনিল আওদিয়াহ।',
    categoryEn: 'Rain',
    categoryBn: 'বৃষ্টি',
  ),
  DuaItem(
    titleEn: 'Dua at the Time of Thunder',
    titleBn: 'বজ্রপাতের সময় দোয়া',
    arabic: 'اللَّهُمَّ لَا تَقْتُلْنَا بِغَضَبِكَ، وَلَا تُهْلِكْنَا بِعَذَابِكَ، وَعَافِنَا قَبْلَ ذَلِكَ',
    translationEn: 'O Allah, do not kill us with Your anger, do not destroy us with Your punishment, and pardon us before that.',
    translationBn: 'হে আল্লাহ! আপনি আপনার ক্রোধ দ্বারা আমাদের হত্যা করবেন না এবং আপনার শাস্তি দ্বারা আমাদের ধ্বংস করবেন না, बल्कि এর পূর্বেই আমাদের ক্ষমা ও নিরাপত্তা দান করুন।',
    pronunciationEn: 'Allahumma laa taqtulnaa bighadabika, wa laa tuhliknaa bi\'adhaabika, wa \'aafinaa qabla dhaalik.',
    pronunciationBn: 'আল্লাহুম্মা লা তাকতুলনা বিগদাবিকা, ওয়া লা তুহলিকনা বিআজাবিকা, ওয়া আফিনা কাবলা জালিকা।',
    categoryEn: 'Rain',
    categoryBn: 'বৃষ্টি',
  ),

  // ── 14. Sickness / অসুস্থতা ──────────────────────────────────────────────
  DuaItem(
    titleEn: 'Dua When Visiting the Sick',
    titleBn: 'রোগী দেখার দোয়া',
    arabic: 'لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهُ',
    translationEn: 'Do not worry, it is a purification, if Allah wills.',
    translationBn: 'কোনো ভয় নেই, আল্লাহর ইচ্ছায় এটি গুনাহ থেকে পবিত্রতার মাধ্যম হবে।',
    pronunciationEn: 'Laa ba\'sa tahoorun in shaa\'a Allaah.',
    pronunciationBn: 'লা বাসা তহুরুন ইনশাআল্লাহ।',
    categoryEn: 'Sickness',
    categoryBn: 'অসুস্থতা',
  ),
  DuaItem(
    titleEn: 'Dua for the Sick',
    titleBn: 'রোগীর জন্য দোয়া',
    arabic: 'أَسْأَلُ اللَّهَ الْعَظِيمَ رَبَّ الْعَرْشِ الْعَظِيمِ أَنْ يَشْفِيَكَ',
    translationEn: 'I ask Allah the Almighty, Lord of the Magnificent Throne, to cure you (seven times).',
    translationBn: 'আমি মহান আরশের রব, সর্বশক্তিমান আল্লাহর কাছে প্রার্থনা করছি তিনি যেন আপনাকে সুস্থতা দান করেন (৭ বার)।',
    pronunciationEn: 'As\'alullaahal-\'Adheema Rabbal-\'Arshil-\'Adheemi an yashfiyaka.',
    pronunciationBn: 'আসআলুল্লাহাল আজীমা রব্বাল আরশিল আজীমি আইঁ ইয়াশফিয়াকা।',
    categoryEn: 'Sickness',
    categoryBn: 'অসুস্থতা',
  ),
  DuaItem(
    titleEn: 'Ruqyah Dua',
    titleBn: 'রুকইয়ার দোয়া (ঝাড়ফুঁক)',
    arabic: 'بِسْمِ اللَّهِ أُرْقِيكَ، مِنْ كُلِّ شَيْءٍ يُؤْذِيكَ، مِنْ شَرِّ كُلِّ نَفْسٍ أَوْ عَيْنِ حَاسِدٍ',
    translationEn: 'In the name of Allah I perform Ruqyah for you, from everything that harms you, from the evil of every soul or envious eye.',
    translationBn: 'আল্লাহর নামে আমি আপনাকে ফুঁ দিচ্ছি (রুকইয়া করছি) সমস্ত ক্ষতিসাধনকারী জিনিস থেকে, প্রতিটি প্রানের অনিষ্ট এবং হিংসুকের বদনজর থেকে।',
    pronunciationEn: 'Bismillaahi urqeeka, min kulli shay\'in yu\'dheeka, min sharri kulli nafsin aw \'ayni haasid.',
    pronunciationBn: 'বিিসমিল্লািহি আরকিকা মিন কুল্লি শাইইন ইয়ুযীকা, মিন শাররি কুল্লি নাফসিন আও আইনি হাসিদিন।',
    categoryEn: 'Sickness',
    categoryBn: 'অসুস্থতা',
  ),

  // ── 15. Death / মৃত্যু ──────────────────────────────────────────────────
  DuaItem(
    titleEn: 'Dua for the Deceased',
    titleBn: 'মৃতের জন্য দোয়া',
    arabic: 'اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ، وَعَافِهِ وَاعْفُ عَنْهُ، وَأَكْرِمْ نُزُلَهُ',
    translationEn: 'O Allah, forgive him and have mercy on him, grant him safety and pardon him, and make his dwelling honorable.',
    translationBn: 'হে আল্লাহ! তাকে ক্ষমা করে দিন এবং তার ওপর দয়া করুন। তাকে শান্তিতে রাখুন, তার গুনাহসমূহ মার্জনা করুন এবং তার মেহমানদারি সম্মানজনক করুন।',
    pronunciationEn: 'Allahummagh-fir lahu warhamhu, wa \'aafihi wa\'fu \'anhu, wa akrim nuzulahu.',
    pronunciationBn: 'আল্লাহুম্মাগ ফিরলাহু ওয়ারহামহু, ওয়া আফিহী ওয়াফু আনহু, ওয়া আকরিমা নুযুলাহু।',
    categoryEn: 'Death',
    categoryBn: 'মৃত্যু',
  ),
  DuaItem(
    titleEn: 'Funeral Prayer (Janazah) Dua',
    titleBn: 'জানাজার দোয়া',
    arabic: 'اللَّهُمَّ اغْفِرْ لِحَيِّنَا وَمَيِّتِنَا، وَشَاهِدِنَا وَغَائِبِنَا، وَصَغِيرِنَا وَكَبِيرِنَا',
    translationEn: 'O Allah, forgive our living and our dead, those who are present and those who are absent, our young and our old.',
    translationBn: 'হে আল্লাহ! আমাদের জীবিত ও মৃতদের ক্ষমা করুন, আমাদের উপস্থিত ও অনুপস্থিতদের ক্ষমা করুন এবং আমাদের ছোট ও বড় সবাইকে ক্ষমা করুন।',
    pronunciationEn: 'Allahummagh-fir lihayyinaa wa mayyitinaa, wa shaahidinaa wa ghaa\'ibinaa, wa sagheerinaa wa kabeerinaa.',
    pronunciationBn: 'আল্লাহুম্মাগফির লিহায়্যিনা ওয়া মাইয়্যিতিনা, ওয়া শাহিদিনা ওয়া গাইবিনা, ওয়া সাগীরিনা ওয়া কাবীরিনা।',
    categoryEn: 'Death',
    categoryBn: 'মৃত্যু',
  ),
  DuaItem(
    titleEn: 'Visiting Graveyard',
    titleBn: 'কবর জিয়াতরের দোয়া',
    arabic: 'السَّلَامُ عَلَيْكُمْ دَارَ قَوْمٍ مُؤْمِنِينَ، وَإِنَّا إِنْ شَاءَ اللَّهُ بِكُمْ لَاحِقُونَ',
    translationEn: 'Peace be upon you, O inhabitants of the dwellings of the believers. Indeed, if Allah wills, we will follow you.',
    translationBn: 'হে মুমিন কবরবাসীগণ! আপনাদের ওপর শান্তি বর্ষিত হোক। নিশ্চয়ই আমরাও আল্লাহর ইচ্ছায় আপনাদের সাথে এসে মিলিত হব।',
    pronunciationEn: 'As-salaamu \'alaykum daara qawmin mu\'mineen, wa innaa in shaa\'a Allaahu bikum laahiquon.',
    pronunciationBn: 'আসসালামু আলাইকুম দারা কাওমিন মুমিনীন, ওয়া ইন্না ইনশাআল্লাহু বিকুম লাহিকুন।',
    categoryEn: 'Death',
    categoryBn: 'মৃত্যু',
  ),

  // ── 16. Hajj & Umrah / হজ ও উমরাহ ───────────────────────────────────────
  DuaItem(
    titleEn: 'Intention for Ihram',
    titleBn: 'ইহরামের নিয়ত',
    arabic: 'اللَّهُمَّ إِنِّي أُرِيدُ الْعُمْرَةَ فَيَسِّرْهَا لِي وَتَقَبَّلْهَا مِنِّي',
    translationEn: 'O Allah, I intend to perform Umrah, so make it easy for me and accept it from me.',
    translationBn: 'হে আল্লাহ! আমি উমরার নিয়ত করছি, আপনি তা আমার জন্য সহজ করে দিন এবং আমার পক্ষ থেকে কবুল করে নিন।',
    pronunciationEn: 'Allahumma innee ureedul-\'Umrata fayassirhaa lee wa taqabbalhaa minnee.',
    pronunciationBn: 'আল্লাহুম্মা ইন্নি উরীদুল উমরাতা ফায়াসসিরহা লী ওয়া তাকাব্বালহা মিন্নী।',
    categoryEn: 'Hajj & Umrah',
    categoryBn: 'হজ ও উমরাহ',
  ),
  DuaItem(
    titleEn: 'Talbiyah',
    titleBn: 'তালবিয়া',
    arabic: 'لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ',
    translationEn: 'I am at Your service, O Allah, I am at Your service. You have no partner. Indeed, praise, grace, and sovereignty belong to You. You have no partner.',
    translationBn: 'আমি হাজির হে আল্লাহ! আমি হাজির! আপনার কোনো শরিক নেই, আমি হাজির! নিশ্চয়ই সমস্ত প্রশংসা, নেয়ামত ও সাম্রাজ্য আপনারই, আপনার কোনো শরিক নেই।',
    pronunciationEn: 'Labbayk Allahumma labbayk, labbayk laa shareeka laka labbayk, innal-hamda wan-ni\'mata laka wal-mulk, laa shareeka laka.',
    pronunciationBn: 'লাব্বাইক আল্লাহুম্মা লাব্বাইক, লাব্বাইক লা শারীকা লাকা লাব্বাইক, ইন্নাল হামদা ওয়ান নিয়মাতা লাকা ওয়াল মুলক, লা শারীকা লাক।',
    categoryEn: 'Hajj & Umrah',
    categoryBn: 'হজ ও উমরাহ',
  ),
  DuaItem(
    titleEn: 'Dua in Tawaf',
    titleBn: 'তাওয়াফের দোয়া (রুকনে ইয়ামানি থেকে হাজরে আসওয়াদ)',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    translationEn: 'Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.',
    translationBn: 'হে আমাদের প্রতিপালক! আমাদের ইহকালে কল্যাণ দান করুন ও পরকালেও কল্যাণ দান করুন এবং জাহান্নামের আজাব থেকে রক্ষা করুন।',
    pronunciationEn: 'Rabbanaa aatinaa fid-dunyaa hasanatan wa fil-aakhirati hasanatan wa qinaa \'adhaban-naar.',
    pronunciationBn: 'রাব্বানা আতিনা ফিদ দুনিয়া হাসানাতাও ওয়া ফিল আখিরাতি হাসানাতাও ওয়া কিনা আজাবান নার।',
    categoryEn: 'Hajj & Umrah',
    categoryBn: 'হজ ও উমরাহ',
  ),
  DuaItem(
    titleEn: 'Dua at Safa and Marwa',
    titleBn: 'সাফা-মারওয়ার দোয়া',
    arabic: 'إِنَّ الصَّفَا وَالْمَرْوَةَ مِنْ شَعَائِرِ اللَّهِ',
    translationEn: 'Indeed, Safa and Marwa are among the symbols of Allah.',
    translationBn: 'নিশ্চয়ই সাফা এবং মারওয়া পাহাড় দুটি আল্লাহর নিদর্শনসমূহের অন্তর্ভুক্ত।',
    pronunciationEn: 'Innas-Safaa wal-Marwata min sha\'aa\'irillaah.',
    pronunciationBn: 'ইন্নাস সাফা ওয়াল মারওয়াতা মিন শাআইরিল্লাহ।',
    categoryEn: 'Hajj & Umrah',
    categoryBn: 'হজ ও উমরাহ',
  ),
  DuaItem(
    titleEn: 'Dua on the Day of Arafah',
    titleBn: 'আরাফার দিনের দোয়া',
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    translationEn: 'There is no god but Allah alone, without partner. To Him belongs sovereignty and all praise, and He is over all things competent.',
    translationBn: 'একমাত্র আল্লাহ ছাড়া কোনো উপাস্য নেই, তাঁর কোনো শরিক নেই। রাজত্ব ও প্রশংসা একমাত্র তাঁরই জন্য এবং তিনি সব কিছুর ওপর ক্ষমতাবান।',
    pronunciationEn: 'Laa ilaaha illallaahu wahdahu laa shareeka lahu, lahul-mulku wa lahul-hamdu, wa Huwa \'alaa kulli shay\'in Qadeer.',
    pronunciationBn: 'লা ইলাহা ইল্লাল্লাহু ওয়াহদাহু লা শারীকা লাহু, লাহুল মুলকু ওয়া লাহুল হামদু ওয়া হুয়া আলা কুল্লি শাইইন ক্বাদীর।',
    categoryEn: 'Hajj & Umrah',
    categoryBn: 'হজ ও উমরাহ',
  ),

  // ── 17. Quranic / কুরআনের দোয়া ──────────────────────────────────────────
  DuaItem(
    titleEn: 'Dua for Goodness (Rabbana Atina)',
    titleBn: 'রাব্বানা আতিনা...',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    translationEn: 'Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.',
    translationBn: 'হে আমাদের প্রতিপালক! আমাদের ইহকালে কল্যাণ দান করুন ও পরকালেও কল্যাণ দান করুন এবং জাহান্নামের আজাব থেকে রক্ষা করুন। (সূরা আল-বাকারাহ: ২০১)',
    pronunciationEn: 'Rabbanaa aatinaa fid-dunyaa hasanatan wa fil-aakhirati hasanatan wa qinaa \'adhaban-naar.',
    pronunciationBn: 'রাব্বানা আতিনা ফিদ দুনিয়া হাসানাতাও ওয়া ফিল আখিরাতি হাসানাতাও ওয়া কিনা আজাবান নার।',
    categoryEn: 'Quranic',
    categoryBn: 'কুরআনের দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua for Knowledge (Rabbi Zidni \'Ilma)',
    titleBn: 'রাব্বি জিদনী ইলমা',
    arabic: 'رَّبِّ زِدْنِي عِلْمًا',
    translationEn: 'My Lord, increase me in knowledge.',
    translationBn: 'হে আমার প্রতিপালক! আমার জ্ঞান বৃদ্ধি করে দিন। (সূরা ত্বাহা: ১১৪)',
    pronunciationEn: 'Rabbi zidnee \'ilmaa.',
    pronunciationBn: 'রাব্বি জিদনী ইলমা।',
    categoryEn: 'Quranic',
    categoryBn: 'কুরআনের দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua of Musa AS (Rabbi-shrah lee sadree)',
    titleBn: 'রাব্বিশরাহ লি সাদরি',
    arabic: 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِّن لِّسَانِي يَفْقَهُوا قَوْلِي',
    translationEn: 'My Lord, expand for me my breast [with assurance] and ease for me my task and untie the knot from my tongue that they may understand my speech.',
    translationBn: 'হে আমার প্রতিপালক! আমার বুক প্রশস্ত করে দিন, আমার কাজ সহজ করে দিন এবং আমার জিহ্বার জড়তা দূর করে দিন যাতে তারা আমার কথা বুঝতে পারে। (সূরা ত্বাহা: ২৫-২৮)',
    pronunciationEn: 'Rabbish-rah lee sadree, wa yassir lee amree, wahlul \'uqdatan min lisaanee, yafqahoo qawlee.',
    pronunciationBn: 'রাব্বিশরাহ লী সাদরী ওয়া ইয়াসসির লী আমরী ওয়াহলুল উকদাতাম মিল লিসানী ইয়াফকাহু কাওলী।',
    categoryEn: 'Quranic',
    categoryBn: 'কুরআনের দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua of Trust (Hasbiyallaahu)',
    titleBn: 'হাসবিয়াল্লাহু',
    arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبِّ الْعَرْشِ الْعَظِيمِ',
    translationEn: 'Sufficient for me is Allah; there is no deity except Him. On Him I have relied, and He is the Lord of the Great Throne.',
    translationBn: 'আমার জন্য আল্লাহই যথেষ্ট, তিনি ছাড়া কোনো সত্য ইলাহ নেই। আমি তাঁর ওপর ভরসা করলাম এবং তিনি মহা আরশের মালিক। (সূরা আত-তাওবাহ: ১২৯)',
    pronunciationEn: 'Hasbiyallaahu laa ilaaha illaa Huwa, \'alayhi tawakkaltu wa Huwa Rabbul-\'Arshil-\'Adheem.',
    pronunciationBn: 'হাসবিয়াল্লাহু লা ইলাহা ইল্লা হুয়া আলাইহি তাওয়াক্কালতু ওয়া হুয়া রাব্বুল আরশিল আজীম।',
    categoryEn: 'Quranic',
    categoryBn: 'কুরআনের দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua of Yunus AS (Laa ilaaha illaa Anta)',
    titleBn: 'লা ইলাহা ইল্লা আন্তা সুবহানাকা...',
    arabic: 'لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ',
    translationEn: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.',
    translationBn: 'আপনি ব্যতীত কোনো সত্য মাবুদ নেই, আপনি মহাপবিত্র! নিশ্চয়ই আমি অপরাধীদের অন্তর্ভুক্ত। (সূরা আল-আম্বিয়া: ৮৭)',
    pronunciationEn: 'Laa ilaaha illaa Anta subhaanaka innee kuntu minadh-dhaalimeen.',
    pronunciationBn: 'লা ইলাহা ইল্লা আনতা সুবহানাকা ইন্নি কুনতু মিনাজ জোয়ালিমীন।',
    categoryEn: 'Quranic',
    categoryBn: 'কুরআনের দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua for Offspring (Rabbana Hab lana)',
    titleBn: 'রাব্বানা হাবলানা...',
    arabic: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا',
    translationEn: 'Our Lord, grant us from among our wives and offspring comfort to our eyes and make us an example for the righteous.',
    translationBn: 'হে আমাদের প্রতিপালক! আমাদের স্ত্রীদের ও সন্তানদের আমাদের জন্য চোখের শীতলতা স্বরূপ বানিয়ে দিন এবং আমাদের মুত্তাকিদের নেতা বানিয়ে দিন। (সূরা আল-ফুরকান: ৭৪)',
    pronunciationEn: 'Rabbanaa hab lanaa min azwaajinaa wa dhurriyyaatinaa qurrata a\'yunin waj\'alnaa lilmuttaqeena imaamaa.',
    pronunciationBn: 'রাব্বানা হাব লানা মিন আজওয়াজিনা ওয়া জুররিয়্যাতিনা কুররাতা আইয়ুনিও ওয়াজআলনা লিল মুত্তাকীনা ইমামা।',
    categoryEn: 'Quranic',
    categoryBn: 'কুরআনের দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua for Parents and Self',
    titleBn: 'রাব্বিগফির লি ওয়ালিওয়ালিদাইয়া',
    arabic: 'رَّبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَلِمَن دَخَلَ بَيْتِيَ مُؤْمِنًا وَلِلْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ',
    translationEn: 'My Lord, forgive me and my parents and whoever enters my house a believer and the believing men and believing women.',
    translationBn: 'হে আমার প্রতিপালক! আমাকে, আমার পিতা-মাতাকে এবং যারা মুমিন হয়ে আমার ঘরে প্রবেশ করবে তাদের ও সমস্ত মুমিন নর-নারীকে ক্ষমা করে দিন। (সূরা নূহ: ২৮)',
    pronunciationEn: 'Rabbigh-fir lee wa liwaalidayya wa liman dakhala baytiya mu\'minan wa lilmu\'mineena wal-mu\'minaat.',
    pronunciationBn: 'রাব্বিগফির লী ওয়া লিওয়ালিদাইয়্যা ওয়া লিমান দাখালা বাইতিয়া মুমিনান ওয়া লিল মুমিনীন ওয়াল মুমিনাত।',
    categoryEn: 'Quranic',
    categoryBn: 'কুরআনের দোয়া',
  ),

  // ── 18. Daily Life / বিভিন্ন পরিস্থিতি ─────────────────────────────────────
  DuaItem(
    titleEn: 'Dua When Sneezing',
    titleBn: 'হাঁচি দিলে দোয়া',
    arabic: 'الْحَمْدُ لِلَّهِ',
    translationEn: 'Praise be to Allah.',
    translationBn: 'সমস্ত প্রশংসা আল্লাহর জন্য।',
    pronunciationEn: 'Alhamdulillah.',
    pronunciationBn: 'আলহামদুলিল্লাহ।',
    categoryEn: 'Daily Life',
    categoryBn: 'বিভিন্ন পরিস্থিতি',
  ),
  DuaItem(
    titleEn: 'Reply to One Who Sneezes',
    titleBn: 'হাঁচির উত্তর',
    arabic: 'يَرْحَمُكَ اللَّهُ',
    translationEn: 'May Allah have mercy on you.',
    translationBn: 'আল্লাহ আপনার ওপর রহমত বর্ষণ করুন।',
    pronunciationEn: 'Yarhamukallaah.',
    pronunciationBn: 'ইয়ারহামুকাল্লাহ।',
    categoryEn: 'Daily Life',
    categoryBn: 'বিভিন্ন পরিস্থিতি',
  ),
  DuaItem(
    titleEn: 'When Yawning',
    titleBn: 'হাই উঠলে করণীয়',
    arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
    translationEn: 'Seek refuge in Allah and try to suppress it or cover your mouth with your left hand.',
    translationBn: 'শয়তান থেকে আশ্রয় প্রার্থনা করুন এবং হাত দিয়ে মুখ ঢাকুন ও হাই চেপে রাখার চেষ্টা করুন।',
    pronunciationEn: 'A\'udhu billahi minash-shaytanir-rajim.',
    pronunciationBn: 'আউজু বিল্লাহি মিনাশ শাইতানির রাজিম।',
    categoryEn: 'Daily Life',
    categoryBn: 'বিভিন্ন পরিস্থিতি',
  ),
  DuaItem(
    titleEn: 'Congratulating Someone',
    titleBn: 'কাউকে অভিনন্দন জানানোর দোয়া',
    arabic: 'بَارَكَ اللَّهُ فِيكَ',
    translationEn: 'May Allah bless you.',
    translationBn: 'আল্লাহ আপনার প্রতি বরকত দান করুন।',
    pronunciationEn: 'Baarakallaahu feeka.',
    pronunciationBn: 'বারাকাল্লাহু ফীকা।',
    categoryEn: 'Daily Life',
    categoryBn: 'বিভিন্ন পরিস্থিতি',
  ),
  DuaItem(
    titleEn: 'Dua for Newlyweds',
    titleBn: 'নবদম্পতির জন্য দোয়া',
    arabic: 'بَارَكَ اللَّهُ لَكَ وَبَارَكَ عَلَيْكَ وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ',
    translationEn: 'May Allah bless you and shower His blessings upon you and join you together in goodness.',
    translationBn: 'আল্লাহ আপনাকে বরকত দিন, আপনার ওপর বরকত বর্ষণ করুন এবং কল্যাণের ওপর আপনাদের উভয়কে একত্রিত করুন।',
    pronunciationEn: 'Baarakallaahu laka wa baaraka \'alayka wa jama\'a baynakumaa fee khayr.',
    pronunciationBn: 'বারাকাল্লাহু লাকা ওয়া বারাকা আলাইকা ওয়া জামাআ বাইনাকুমা ফী খাইর।',
    categoryEn: 'Daily Life',
    categoryBn: 'বিভিন্ন পরিস্থিতি',
  ),
  DuaItem(
    titleEn: 'Farewell Dua',
    titleBn: 'কাউকে বিদায়ের দোয়া',
    arabic: 'أَسْتَوْدِعُ اللَّهَ دِينَكَ وَأَمَانَتَكَ وَخَوَاتِيمَ عَمَلِكَ',
    translationEn: 'I entrust to Allah your religion, your trust (faith), and your final deeds.',
    translationBn: 'আমি আল্লাহর কাছে আপনার দ্বীন, আপনার আমানত এবং আপনার শেষ আমলসমূহ সোপর্দ করলাম।',
    pronunciationEn: 'Astawdi\'ullaaha deenaka wa amaanataka wa khawaateema \'amalik.',
    pronunciationBn: 'আস্তাউদিউল্লাহা দ্বীনাকা ওয়া আমানাতাকা ওয়া খাওয়াতীমা আমালিকা।',
    categoryEn: 'Daily Life',
    categoryBn: 'বিভিন্ন পরিস্থিতি',
  ),
  DuaItem(
    titleEn: 'Dua for the Host (Guest\'s Dua)',
    titleBn: 'অতিথির জন্য দোয়া',
    arabic: 'اللَّهُمَّ بَارِكْ لَهُمْ فِيمَا رَزَقْتَهُمْ، وَاغْفِرْ لَهُمْ وَارْحَمْهُمْ',
    translationEn: 'O Allah, bless them in what You have provided for them, forgive them and have mercy on them.',
    translationBn: 'হে আল্লাহ! আপনি তাদের যে রিজিক দান করেছেন তাতে বরকত দিন, তাদের ক্ষমা করুন এবং তাদের ওপর দয়া করুন।',
    pronunciationEn: 'Allahumma baarik lahum feemaa razaqtahum, wagh-fir lahum warhamhum.',
    pronunciationBn: 'আল্লাহুম্মা বারিক লাহুম ফীমা রাজাকতাহুম, ওয়াগফির লাহুম ওয়ারহামহুম।',
    categoryEn: 'Daily Life',
    categoryBn: 'বিভিন্ন পরিস্থিতি',
  ),
  DuaItem(
    titleEn: 'Expiation of Meeting (Kaffaratul Majlis)',
    titleBn: 'মজলিস শেষে কাফফারার দোয়া',
    arabic: 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ',
    translationEn: 'Glory is to You, O Allah, and praise. I bear witness that there is no god but You. I seek Your forgiveness and turn to You in repentance.',
    translationBn: 'হে আল্লাহ! আমি আপনার সপ্রশংস পবিত্রতা ঘোষণা করছি। আমি সাক্ষ্য দিচ্ছি যে আপনি ছাড়া কোনো উপাস্য নেই, আমি আপনার নিকট ক্ষমা প্রার্থনা করছি এবং আপনার নিকট তওবা করছি।',
    pronunciationEn: 'Subhaanaka Allahumma wa bihamdika, ashhadu an laa ilaaha illaa Anta, astaghfiruka wa atoobu ilayk.',
    pronunciationBn: 'সুবহানাকাল্লাহুম্মা ওয়া বিহামদিকা আশহাদু আল্লা ইলাহা ইল্লা আনতা আস্তাগফিরুকা ওয়া আতূবু ইলাইকা।',
    categoryEn: 'Daily Life',
    categoryBn: 'বিভিন্ন পরিস্থিতি',
  ),

  // ── 19. Dhikr / যিকির ───────────────────────────────────────────────────
  DuaItem(
    titleEn: 'Tasbih',
    titleBn: 'সুবহানাল্লাহ',
    arabic: 'سُبْحَانَ اللَّهِ',
    translationEn: 'Glory be to Allah.',
    translationBn: 'আল্লাহ মহাপবিত্র।',
    pronunciationEn: 'Subhanallah.',
    pronunciationBn: 'সুবহানাল্লাহ।',
    categoryEn: 'Dhikr',
    categoryBn: 'যিকির',
  ),
  DuaItem(
    titleEn: 'Tahmeed',
    titleBn: 'আলহামদুলিল্লাহ',
    arabic: 'الْحَمْدُ لِلَّهِ',
    translationEn: 'Praise be to Allah.',
    translationBn: 'সকল প্রশংসা আল্লাহর জন্য।',
    pronunciationEn: 'Alhamdulillah.',
    pronunciationBn: 'আলহামদুলিল্লাহ।',
    categoryEn: 'Dhikr',
    categoryBn: 'যিকির',
  ),
  DuaItem(
    titleEn: 'Takbeer',
    titleBn: 'আল্লাহু আকবার',
    arabic: 'اللَّهُ أَكْبَرُ',
    translationEn: 'Allah is the Greatest.',
    translationBn: 'আল্লাহ সর্বশ্রেষ্ঠ।',
    pronunciationEn: 'Allahu Akbar.',
    pronunciationBn: 'আল্লাহু আকবার।',
    categoryEn: 'Dhikr',
    categoryBn: 'যিকির',
  ),
  DuaItem(
    titleEn: 'Tahlil',
    titleBn: 'লা ইলাহা ইল্লাল্লাহ',
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ',
    translationEn: 'There is no god but Allah.',
    translationBn: 'আল্লাহ ব্যতীত কোনো সত্য উপাস্য নেই।',
    pronunciationEn: 'La ilaha illallah.',
    pronunciationBn: 'লা ইলাহা ইল্লাল্লাহ।',
    categoryEn: 'Dhikr',
    categoryBn: 'যিকির',
  ),
  DuaItem(
    titleEn: 'La Hawla wa La Quwwata...',
    titleBn: 'লা হাওলা ওয়ালা কুওয়াতা...',
    arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    translationEn: 'There is no might nor power except with Allah (a treasure of Paradise).',
    translationBn: 'আল্লাহর সাহায্য ছাড়া গুনাহ থেকে বাঁচার এবং নেক কাজ করার কোনো শক্তি নেই (এটি জান্নাতের অন্যতম গুপ্তধন)।',
    pronunciationEn: 'Laa hawla wa laa quwwata illaa billaah.',
    pronunciationBn: 'লা হাওলা ওয়ালা কুওয়াতা ইল্লা বিল্লাহ।',
    categoryEn: 'Dhikr',
    categoryBn: 'যিকির',
  ),
  DuaItem(
    titleEn: 'Hasbunallaahu wa ni\'mal Wakeel',
    titleBn: 'হাসবুনাল্লাহু ওয়া নি\'মাল ওয়াকিল',
    arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
    translationEn: 'Sufficient for us is Allah, and He is the best Disposer of affairs.',
    translationBn: 'আমাদের জন্য আল্লাহই যথেষ্ট এবং তিনি কতই না উত্তম কর্মবিধায়ক।',
    pronunciationEn: 'Hasbunallaahu wa ni\'mal-Wakeel.',
    pronunciationBn: 'হাসবুনাল্লাহু ওয়া নি’মাল ওয়াকীল।',
    categoryEn: 'Dhikr',
    categoryBn: 'যিকির',
  ),

  // ── 20. Special / বিশেষ দোয়া ───────────────────────────────────────────
  DuaItem(
    titleEn: 'Dua for Exams',
    titleBn: 'পরীক্ষা দেওয়ার দোয়া',
    arabic: 'رَبِّ يَسِّرْ وَلَا تُعَسِّرْ وَتَمِّمْ بِالْخَيْرِ',
    translationEn: 'My Lord, make it easy and do not make it difficult, and complete it with goodness.',
    translationBn: 'হে আমার প্রতিপালক! কাজটি আমার জন্য সহজ করুন, কঠিন করবেন না এবং কল্যাণের সাথে সমাপ্ত করুন।',
    pronunciationEn: 'Rabbi yassir wa laa tu\'assir wa tammim bil-khayr.',
    pronunciationBn: 'রাব্বি ইয়াসসির ওয়া লা তুআসসির ওয়া তামমিম বিল খায়ের।',
    categoryEn: 'Special',
    categoryBn: 'বিশেষ দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua for Knowledge',
    titleBn: 'জ্ঞান বৃদ্ধির দোয়া',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَأَعُوذُ بِكَ مِنْ عِلْمٍ لَا يَنْفَعُ',
    translationEn: 'O Allah, I ask You for beneficial knowledge and seek refuge in You from knowledge that is not beneficial.',
    translationBn: 'হে আল্লাহ! আমি আপনার নিকট উপকারী জ্ঞান প্রার্থনা করছি এবং অপকারী জ্ঞান থেকে আশ্রয় প্রার্থনা করছি।',
    pronunciationEn: 'Allahumma innee as\'aluka \'ilman naafi\'an wa a\'udhu bika min \'ilmin laa yanfa\'u.',
    pronunciationBn: 'আল্লাহুম্মা ইন্নি আসআলুকা ইলমান নাফিয়ান ওয়া আউজু বিকা মিন ইলমিন লা ইয়ানফাউ।',
    categoryEn: 'Special',
    categoryBn: 'বিশেষ দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua for Success',
    titleBn: 'সফলতার দোয়া',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى',
    translationEn: 'O Allah, I ask You for guidance, piety, chastity, and self-sufficiency.',
    translationBn: 'হে আল্লাহ! আমি আপনার নিকট হেদায়েত, তাকওয়া, পবিত্রতা এবং স্বাবলম্বিতা প্রার্থনা করছি।',
    pronunciationEn: 'Allahumma innee as\'alukal-hudaa wat-tuqaa wal-\'afaafa wal-ghinaa.',
    pronunciationBn: 'আল্লাহুম্মা ইন্নি আসআলুকাল হুদা ওয়াত তুক্বা ওয়াল আফাফা ওয়াল গিনা।',
    categoryEn: 'Special',
    categoryBn: 'বিশেষ দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua for Patience',
    titleBn: 'ধৈর্যের দোয়া',
    arabic: 'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',
    translationEn: 'Our Lord, pour upon us patience and plant firmly our feet and give us victory over the disbelieving people.',
    translationBn: 'হে আমাদের প্রতিপালক! আমাদের ওপর ধৈর্য ঢেলে দিন, আমাদের পা সুদৃঢ় রাখুন এবং সত্য প্রত্যাখ্যানকারী সম্প্রদায়ের বিরুদ্ধে আমাদের জয়ী করুন।',
    pronunciationEn: 'Rabbanaa afrigh \'alaynaa sabran wa thabbit aqdaamanaa wan-surnaa \'alal-qawmil-kaafireen.',
    pronunciationBn: 'রাব্বানা আফরিগ আলাইনা সাবরাও ওয়া ছাব্বিত আকদামানা ওয়ানসুরনা আলাল কাওমিল কাফিরীন।',
    categoryEn: 'Special',
    categoryBn: 'বিশেষ দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua for Death on Faith',
    titleBn: 'ঈমানের উপর মৃত্যুর দোয়া',
    arabic: 'تَوَفَّنِي مُسْلِمًا وَأَلْحِقْنِي بِالصَّالِحِينَ',
    translationEn: 'Cause me to die a Muslim and join me with the righteous.',
    translationBn: 'আপনি আমাকে একজন আত্মসমর্পণকারী (মুসলিম) হিসেবে মৃত্যু দান করুন এবং সৎকর্মশীলদের সাথে শামিল করুন। (সূরা ইউসুফ: ১০১)',
    pronunciationEn: 'Tawaffanee musliman wa alhiqnee bis-saaliheen.',
    pronunciationBn: 'তাওয়াফফানী মুসলিমাও ওয়া আলহিকনী বিস সালিহীন।',
    categoryEn: 'Special',
    categoryBn: 'বিশেষ দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua Seeking Paradise (Jannah)',
    titleBn: 'জান্নাত লাভের দোয়া',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ',
    translationEn: 'O Allah, I ask You for Paradise and seek refuge in You from the Fire.',
    translationBn: 'হে আল্লাহ! আমি আপনার নিকট জান্নাত প্রার্থনা করছি এবং জাহান্নাম থেকে আশ্রয় প্রার্থনা করছি।',
    pronunciationEn: 'Allahumma innee as\'alukal-Jannata wa a\'udhu bika minan-Naar.',
    pronunciationBn: 'আল্লাহুম্মা ইন্নি আসআলুকাল জান্নাতা ওয়া আউজু বিকা মিনান নার।',
    categoryEn: 'Special',
    categoryBn: 'বিশেষ দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua for Protection from Hellfire',
    titleBn: 'জাহান্নাম থেকে মুক্তির দোয়া',
    arabic: 'اللَّهُمَّ أَجِرْنِي مِنَ النَّارِ',
    translationEn: 'O Allah, protect me from the Fire.',
    translationBn: 'হে আল্লাহ! আমাকে জাহান্নামের আগুন থেকে রক্ষা করুন।',
    pronunciationEn: 'Allahumma ajirnee minan-naar.',
    pronunciationBn: 'আল্লাহুম্মা আজিরনী মিনান নার।',
    categoryEn: 'Special',
    categoryBn: 'বিশেষ দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua for Good Character',
    titleBn: 'ভালো চরিত্রের দোয়া',
    arabic: 'اللَّهُمَّ اهْدِنِي لِأَحْسَنِ الْأَعْمَالِ وَأَحْسَنِ الْأَخْلَاقِ لَا يَهْدِي لِأَحْسَنِهَا إِلَّا أَنْتَ',
    translationEn: 'O Allah, guide me to the best of deeds and the best of manners, for none can guide to the best of them except You.',
    translationBn: 'হে আল্লাহ! আমাকে সর্বোত্তম আমল ও সর্বোত্তম চরিত্রের দিকে পরিচালিত করুন, আপনি ছাড়া আর কেউ সর্বোত্তম আমল ও চরিত্রের দিকে হেদায়েত করতে পারে না।',
    pronunciationEn: 'Allahummah-dinee li-ahsanil-a\'maali wa ahsanil-akhlaaqi laa yahdee li-ahsanihaa illaa Ant.',
    pronunciationBn: 'আল্লাহুম্মাহদিনী লিআহসানিল আমালি ওয়া আহসানিল আখলাক্বি লা ইয়াহদী লিআহসানিহা ইল্লা আনতা।',
    categoryEn: 'Special',
    categoryBn: 'বিশেষ দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua for Guidance',
    titleBn: 'হিদায়াতের দোয়া',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالسَّدَادَ',
    translationEn: 'O Allah, I ask You for guidance and correctness.',
    translationBn: 'হে আল্লাহ! আমি আপনার নিকট হেদায়েত এবং সরল ও সঠিক পথ প্রার্থনা করছি।',
    pronunciationEn: 'Allahumma innee as\'alukal-hudaa was-sadaad.',
    pronunciationBn: 'আল্লাহুম্মা ইন্নি আসআলুকাল হুদা ওয়াস সাদাদ্।',
    categoryEn: 'Special',
    categoryBn: 'বিশেষ দোয়া',
  ),
  DuaItem(
    titleEn: 'Dua for All Good',
    titleBn: 'সব কল্যাণ চাওয়ার দোয়া',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنَ الْخَيْرِ كُلِّهِ عَاجِلِهِ وَآجِلِهِ مَا عَلِمْتُ مِنْهُ وَمَا لَمْ أَعْلَمْ',
    translationEn: 'O Allah, I ask You for all good, both immediate and delayed, what I know of it and what I do not know.',
    translationBn: 'হে আল্লাহ! আমি আপনার নিকট সমস্ত কল্যাণ প্রার্থনা করছি—তাড়াতাড়ি প্রাপ্ত বা বিলম্বে প্রাপ্ত, যা আমি জানি এবং যা আমি জানি না।',
    pronunciationEn: 'Allahumma innee as\'aluka minal-khayri kullihee \'aajilihee wa aajilihee maa \'alimtu minhu wa maa lam a\'lam.',
    pronunciationBn: 'আল্লাহুম্মা ইন্নি আসআলুকা মিনাল খাইরি কুল্লিহী আজিিলিহী ওয়া আজিলিহী মা আলিমতু মিনহু ওয়ামা লাম আলাম।',
    categoryEn: 'Special',
    categoryBn: 'বিশেষ দোয়া',
  ),
];
